### ISSUE TITLE
Sandag BCA Tool code ownership/license?

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/bca4abm#10]
What is the copyright/ownership status of the existing sandag bca tool - can I quote/excerpt from the MSSQL stored procedures in the bca4abm source or documentation?

**Comment by mabcal** [comment]
Joel?  We may need to look at the project contract.

**Comment by jfdman** [comment]
Here are the relevant IP clauses from the contract. SANDAG owns everything. However, they have in the past put all of their code out on github under one of the public licenses. I think we asked Daniel if they were planning on doing this with the BCA tool but never heard back. I will ask Clint what he's planning and whether we can borrow from the code. 

19. OWNERSHIP OF DOCUMENTS AND OTHER WORK PRODUCT
A. Tracings, plans, specifications, and maps prepared or obtained under the terms of this
Agreement shall be delivered to and become the property of SANDAG. Basic survey notes
and sketches, charts, computations, and other data prepared or obtained under this
Agreement shall be made available, upon request, to SANDAG without restriction or limitation
on its use.
B. Consultant agrees that any and all property rights, including intellectual property rights such
as copyrights or patents that arise from creation of deliverables or other work products
required by this Agreement shall be vested in SANDAG and hereby agrees to relinquish all
claims to such property rights in favor of SANDAG.
C. The term “deliverables” includes, but is not limited to, all original drawings, reports, and other
documents, including detailed calculations, digital/electronic databases, source code, data
sets, analyses, maps, and other work products developed for the Project. Digital or electronic
data is required as a deliverable under this Agreement. Consultant must submit deliverables
in a format identified by SANDAG as one it can decipher. Documentation and metadata must
accompany the data in order for the deliverable to be accepted by SANDAG.
