### ISSUE TITLE
why bother with orig and dest taz or microzone ids in trips file?

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/bca4abm#12]
why bother with orig and dest taz or microzone ids in trips file if we have travel time and cost columns?

**Comment by toliwaga** [comment]
as far as I can see, the only fields taht matter are:

**Comment by toliwaga** [comment]
As far as I can see, the only fields that matter are:

pno: person_idx
hhno: hh_id
tour: tour_idx
half: half_tour_idx
tseg: half_tour_segment_idx
pdpurp: tour_purpose
mode: trip_mode
autotime: auto_time
transittime: transit_time
biketime: bike_time
walktime: walk_time

**Comment by toliwaga** [comment]
Shouldn't we be breaking transit_time down by wait_time, in_vehicle_time?

**Comment by mabcal** [comment]
Yes,, the new plan, as per Joel's spreadsheet, breaks down time and cost by more categories.

You are right, we don't need TAZ or MAZ id's in the current design.

**Comment by jfdman** [comment]
The BCA tool doesn't need TAZ\MAZ\TAP fields but it is useful to include these fields in trip files for debugging purposes.

**Comment by toliwaga** [comment]
No problem having extra columns in the actual input dataset, I am just trying to document the minimal set used for bca calculation.
