### ISSUE TITLE
need to implement multiyear processor capability?

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/bca4abm#16]
The sandag bca tool takes scenario runs for multiple years and does some sort of interpolation/extrapolation between the years. Do we need to support  anything like that? And if so, what is the spec for which columns are to be handled in what ways?

**Comment by mabcal** [comment]
I think that initial version of the tool doesn't need to support that. It just needs to be able to compare two scenarios for a given year, and have a discount rate that applies to that year. 

We can add that later.

**Comment by jfdman** [comment]
Agree

**Comment by toliwaga** [comment]
Phew! That is great news. 

I am closing this issue before anybody changes their mind!
