### ISSUE TITLE
need to break out ovt time for transit?

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/bca4abm#18]
The sandag bca tool weights ovt differently for vot calculations but ovt isn't broken out for transit trips in bcatest6 sample db

Are we just going to ignore this for the initial version?

**Comment by mabcal** [comment]
That is in Joel's spreadsheet, which supercedes bcatest6 - I would have updated bcatest6, but you advised that isn't necessary.

**Comment by toliwaga** [comment]
Well, we will eventually want a sample data set for both data sources...
