### ISSUE TITLE
terminology and model setup

### ISSUE THREAD

**Issue by bstabler** [RSGInc/bca4abm#20]
@toliwaga and I decided on the following terminology and model setup.

## base and build
The BCA tool will expect the user to provide a base folder location and a build folder location.  The two folders will contain the same input files.  

The four sets of alternatives are named as follows:

1. basetrips_baselos
2. basetrips_buildlos
3. buildtrips_buildlos
4. buildtrips_baselos

## alt
Within the code and in the exposed expressions, `alt` and `altlos` is used.  

1. alt means the other scenario
2. altlos means the LOS (skims) from the other scenario

**Comment by toliwaga** [comment]
I thought we were just going to use the base and build folders for the aggregate_trips skims. (Since they would normally have the same names and specific to their respective builds.)

I'n not sure it makes as much sense for the person trips files which are joining base and build data...

**Comment by toliwaga** [comment]
Actually, come to think of it, the names of the person trips data files are specified in the settings file - we are really only talking about their canonical names in the spec. 

Similarly, we could specify the folder names of the skim omx files in the settings - all we are really requiring is that the aggregate trip omx files have same names and keyed matrices in their respective folders. (So they can both share same manifest file.)

**Comment by bstabler** [comment]
Yes, I think the point of this discussion is to establish that we have a few concepts that we want to name and then consistently use those names in the code, user interface, specification, examples, documentation, etc.  So, the settings file will have a property called "basetrips_baselos" for example.  We decided to write this down because it turned out that all of us were naming these things in slightly different ways and it was somewhat confusing.

**Comment by toliwaga** [comment]
I changed the aggregate trip omx data directory names to 'base-matrices' and 'build-matrices' following a suggestion by @bstabler

The only weird thing about moving the disaggregate trips into base/build subfolders is that, unlike the matrices, the alt-los files really have one foot on both the base and build camps…

The only real utility to having a base and build folder for matrices is to avoid having to rename the files and double the size of the manifest.

**Comment by toliwaga** [comment]
I made these changes
