### ISSUE TITLE
custom matrix handling for aggregate calculations

### ISSUE THREAD

**Issue by bstabler** [RSGInc/bca4abm#21]
The specification that @jfdman provided for SANDAG includes special logic for dealing with the toll matrix since some of the OD pairs have a toll + 10000 to identify it as a special toll.  @mabcal suggested using a SCALE column for calculating the auto operating cost since some agencies only use a distance matrix times a scalar.  To support these types of customizations in the matrix specification, I think we should add an EXPRESSION column for each matrix read that supports a Python expression.  This expression could be applied when the matrix is first read, or could be applied on demand.  Exposing this flexibility in the form of a Python expression is the spirit of ActivitySim and would go a long way toward a more generic tool.  @toliwaga and I decided to wait and implement this after we get the minimal operating solution up and running.

**Comment by toliwaga** [comment]
I thought we decided to wait to **_decide_** whether to implement it, not to wait to implement it?

**Comment by bstabler** [comment]
yes, that is correct since it is not needed for Tampa.  After we get Tampa up and running, then we'll revisit the idea since it may be a good solution for a more generic tool.

**Comment by toliwaga** [comment]
This is working now with hard-wired expressions but organized so it wouldn't be too hard to implement with expressions, depending on what approach we want to take. Right now I am computing the tt, monetized_tt, aoc, and toll values separately (slightly inefficient sin there are multiple sum operations) just to show how that would work, should we want to retain that level of detail for display.
