### ISSUE TITLE
at statement considered harmful

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/bca4abm#26]
The activitysim convention of prefixing expressions with an at sign to indicate that they should be evaluated with a python eval rather than pandas eval is a little bit inconvenient if you want to maintain your csv file of expressions in excel as those statement are interpreted as formulas. We might want to use a different method of tagging these expressions that plays better with excel.

![screen shot 2016-02-24 at 12 56 43 pm](https://cloud.githubusercontent.com/assets/58944/13295319/40b2f162-daf6-11e5-98c7-816e740bfda6.png)

**Comment by mabcal** [comment]
Can you make that a configuration setting – which character defines an expression?

Along the same lines, it would be useful to have the data file delimiter as a configuration setting, which would allow comma, tab, or space-delimited. (DaySim has that for each input data file, but it could also be a more global setting for all data files.

**Comment by toliwaga** [comment]
I can live with the at sign.

**Comment by bstabler** [comment]
Typing a single quote at the beginning of the expression tells Excel to accept the expression.  We had this same in CT-RAMP.

**Comment by toliwaga** [comment]
Come to think about it, there is no real reason for them to be csv files at all. We could just do something like this:

```
speed = congested_speed
VMT_car = distance * (total_volume - truck_volume)
VMT_truck = distance * truck_volume
# this is a comment because it starts with a hash (#) sign
# the at (@) signs in the expressions below indicate they should use python eval
@op_cost_car = (non_fuel_cost_car + avg_fuel_cost_car * fuel_consumption_car(speed)) * VMT_car
@op_cost_truck = (non_fuel_cost_truck + avg_fuel_cost_truck * fuel_consumption_truck(df.congested_speed)) * VMT_truck
```

On the other hand, if we did that, then users would edit them with a word processor and we would end up having to deal with smart quotes and the like...

**Comment by bstabler** [comment]
I think we need to stick with CSVs so we can parse the tables and easily edit the files in Excel.  There is a good history here with CT-RAMP and the Utility Expression Calculator.  This also reminds me of a couple discussion ([here] (https://github.com/UDST/activitysim/issues/5) and [here](https://github.com/UDST/activitysim/issues/33)) about ActivitySim design.
