### ISSUE TITLE
coc grouping for auto ownership

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/bca4abm#29]
vehicle ownership is by households, but some coc determinations (age) are person-based and some are hh based (income)

to allocate auto ownership by coc, do we use the age of the oldest hh member?

Suppose there is a household with two members ages 35 and 85 and two cars, do we try and be really clever and allocate one car to each hh member? And what if there are three adults hh members and two cars?

**Comment by mabcal** [comment]
The easiest thing to do is just divide the household level benefits by household size and assign the same share  to each person.  That would work the same for any person-level selection.  (We could just assign them to each adult, but that probably would raise its own issues, so simplest may be best.)

**Comment by toliwaga** [comment]
That's better than the "weakest link" approach for sure. Will do.
