### ISSUE TITLE
input daily links table was not in the right place in the example

### ISSUE THREAD

**Issue by bstabler** [RSGInc/bca4abm#37]

**Comment by toliwaga** [comment]
sorry - the data dir in example should be an exact copy of the one in tests

**Comment by bstabler** [comment]
that's ok, I'll fix it now and commit.

**Comment by toliwaga** [comment]
The problem was caused by the fact that the build dir was not getting into the repo because it is gitignored so I decided to just put them into xxx-matrices dirs to avoid the homonym
