### ISSUE TITLE
output a link results table to CSV as well

### ISSUE THREAD

**Issue by bstabler** [RSGInc/bca4abm#42]
a link results output table is missing

**Comment by bstabler** [comment]
In addition to the HDF5 file, I was thinking CSV files in the outputs folder for debugging/transparency. Take a look at the outputs page in the wiki - https://github.com/RSGInc/bca4abm/wiki/Outputs - for what is missing at the bottom.

**Comment by toliwaga** [comment]
I think this is done now.
