### ISSUE TITLE
clean-up link tables being in the base/build matrices folders

### ISSUE THREAD

**Issue by bstabler** [RSGInc/bca4abm#49]

**Comment by toliwaga** [comment]
I don't see why this is a bug

**Comment by bstabler** [comment]
the folders are named "base-matrices" and "build-matrices" but they contain link data?  Isn't that confusing for the user?

**Comment by mabcal** [comment]
I’m fine with just renaming the folders instead of splitting up the files.

**Comment by toliwaga** [comment]
ok sure - technically I would argue that they are sparse matrices

**Comment by toliwaga** [comment]
Any way y'all want to do this is fine by me. Let me know.

**Comment by toliwaga** [comment]
just going to rename these build-data and base-data for now - easy enough to change if anybody has an alt pref
