### ISSUE TITLE
read tab separated files in addition to csv

### ISSUE THREAD

**Issue by bstabler** [RSGInc/bca4abm#60]
Daysim writes tsv by default.  Please expose the pandas read csv sep argument in the settings.yaml file

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html

**Comment by toliwaga** [comment]
Just to understand the problem, which files, specifically, might be tab delimited? And if one is, will all be?

all csv files (surely not the  config files?)

presumably  these:
   base_households.csv
   basetrips_buildlos.csv
   basetrips_normal.csv
   build_households.csv
   buildtrips_baselos.csv
   buildtrips_normal.csv
   persons.csv

how about:
   link manifest?
   link files?

**Comment by mabcal** [comment]
Yes the ones you list under “presumably these”, and maybe the link files as well (but not the link manifest).  You could set the delimiter based off the extension -- .tsv means tab, .csv means comma, .txt means space. Basically, anything that’s listed as an input file in the config files, except the .omx matrices.

Mark

**Comment by toliwaga** [comment]
sounds good. I am assuming there is no escaping of any kind? 

how should quotes be handled - passed through as literals, I presume?

**Comment by toliwaga** [comment]
fixed
