### ISSUE TITLE
aggregate_zone processor file handling

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/bca4abm#69]
For the aggregate_zone processor, we will allow the analyst to specify a list of csv files that should be combined into a single table. 

I am wondering whether to include the 1024 column cval table, and whether that needs to be special-cased. All the other zone files will have two versions, one for the build and one for the base scenario. I was thinking we could handle that by automatically prepending base_ or build_ to the column names, but we probably don’t want to create two versions of the 1024 cval columns (unless they can be different in build and base? In which case we also need two versions in the aggregate demographics processor?)

**Comment by bstabler** [comment]
we need both since the cval file for Metro includes the car ownership model results and this changes between build and base
