### ISSUE TITLE
read multiple files for link_daily

### ISSUE THREAD

**Issue by bstabler** [RSGInc/bca4abm#74]
need to be able to read multiple link files to sum up to daily

**Comment by bstabler** [comment]
link_daily_file_name: linksMD1.csv

is now:

link_daily_file_names:
  - linksMD1.csv
  - linksPM2.csv

link_daily_index_fields:
  - i
  - j

**Comment by bstabler** [comment]
@toliwaga - I think maybe the test data for the ABM example is incorrect for the mce branch?

**Comment by bstabler** [comment]
We need to specify a name to use for the file when we append the tables

link_daily_file_names:
  - linksMD1.csv
  - linksPM2.csv

becomes

link_daily_file_names:
  md1 : linksMD1.csv
  pm2 : linksPM2.csv

and link expressions go from:

links.svol + links.svol_linksPM2

to 

either: 

links.svol_md1 + links.svol_pm2

or 

links.svol + links.svol_pm2 (only the 2nd and subsequent files get the appended file name)

**Comment by toliwaga** [comment]
We can allow both behaviors by doing this:
```
# this version has no suffix for linksMD1.csv
link_daily_file_names:
   "" : linksMD1.csv
    pm2 : linksPM2.csv

# this version assigns suffixes to both files
link_daily_file_names:
    md1 : linksMD1.csv
    pm2 : linksPM2.csv
```
but I think it might be clearer if the example used explicit suffixes for both

**Comment by bstabler** [comment]
I think we should use explicit suffixes for both

**Comment by toliwaga** [comment]
resolved by pull request 80
