### ISSUE TITLE
specify build folder in order to better support multiple build folders

### ISSUE THREAD

**Issue by bstabler** [RSGInc/bca4abm#77]
Often many build scenarios are run against a single base scenario.  Should we copy the base folder input data each time, or just add support for multiple build folders?  Or maybe just a base and build input and outputs folder location in the settings file?

**Comment by bstabler** [comment]
or maybe just a base and build input and outputs folder location in the settings file?

**Comment by toliwaga** [comment]
I think we should allow user to specify alternate base and build input and outputs folder location in the settings file? if nothing is specified, uses the default folder names/locations

**Comment by bstabler** [comment]
I agree

**Comment by toliwaga** [comment]
The base-build distinction doesn't apply as well to the abm data which has nasty combined basetrips_buildlos.csv files etc.

**Comment by toliwaga** [comment]
Could punt for now with 3 configs (data, base_data, build_data), or should the combo files all go into the build-data folder?

**Comment by bstabler** [comment]
let's hold off on this for now since it might be more confusing to the user to support this, then it is inconvenient to copy the folder for each analysis
