### ISSUE TITLE
read zone csvs in addition to omx matrices for the aggregate od processor

### ISSUE THREAD

**Issue by bstabler** [RSGInc/bca4abm#91]
Sometimes we need to read a zone vector into the od processors as well.  For example, parking cost at the destination. We should add the ability to also read in the zone data and specify if the zone vector is replicated to a full matrix by row or by column.  For now you can pre-process the zone vector to create a matrix.

**Comment by toliwaga** [comment]
Do we have any sample data to add to the example to exercise this feature?

**Comment by bstabler** [comment]
Here is an example implementation.  Read the zone vectors in as zone data files and add the columns to aggregate_od.xml using the origin_zone_matrices or dest_zone_matrices setting:

```
origin_zone_matrices:
  - ltpkg
  - stpkg
dest_zone_matrices:
  - ltpkg
  - stpkg
```

Then reference these zone vectors in the aggregate_od expressions, for example:

```
dest_zone['ltpkg_build'] - dest_zone['ltpkg_base']
```
